### ISSUE TITLE
RuntimeError: synStatus=26 [Generic failure] Device acquire failed.

### ISSUE THREAD

**Issue by VinayHN1365466** [huggingface/optimum-habana#1611]
### System Info

```shell
HL-SMI Version:hl-1.18.0-fw-53.1.1.1
Driver Version:1.18.0-ee698fb 
Docker: vault.habana.ai/gaudi-docker/1.18.0/ubuntu22.04/habanalabs/pytorch-installer-2.4.0:latest

I'm getting the below error while running text-generation file. 
python run_generation.py --model_name_or_path gpt2 --use_hpu_graphs --use_kv_cache --max_new_tokens 100 --do_sample --prompt "Here is my prompt"



/usr/lib/python3.10/inspect.py:288: FutureWarning: `torch.distributed.reduce_op` is deprecated, please use `torch.distributed.ReduceOp` instead
  return isinstance(object, types.FunctionType)
/usr/local/lib/python3.10/dist-packages/transformers/deepspeed.py:24: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
Fetching 1 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 6898.53it/s]
Fetching 1 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 4760.84it/s]
12/16/2024 08:28:10 - INFO - __main__ - Single-device run.
/home/jenkins/workspace/cdsoftwarebuilder/create-binaries-from-sw-sources---bp-dt/repos/hcl/src/platform/gaudi_common/hcl_device_control_factory.cpp::84(initDevice): The condition [ g_ibv.init(deviceConfig) == hcclSuccess ] failed. ibv initialization failed
Traceback (most recent call last):
  File "/root/optimum-habana/examples/text-generation/run_generation.py", line 773, in <module>
    main()
  File "/root/optimum-habana/examples/text-generation/run_generation.py", line 384, in main
    model, assistant_model, tokenizer, generation_config = initialize_model(args, logger)
  File "/root/optimum-habana/examples/text-generation/utils.py", line 720, in initialize_model
    setup_model(args, model_dtype, model_kwargs, logger)
  File "/root/optimum-habana/examples/text-generation/utils.py", line 297, in setup_model
    model = model.eval().to(args.device)
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 2958, in to
    return super().to(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1177, in to
    return self._apply(convert)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 805, in _apply
    param_applied = fn(param)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1163, in convert
    return t.to(
RuntimeError: synStatus=26 [Generic failure] Device acquire failed.
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. cd examples/text-generation/
2.  python run_generation.py --model_name_or_path gpt2 --use_hpu_graphs --use_kv_cache --max_new_tokens 100 --do_sample --prompt "Here is my prompt"

### Expected behavior

Execute Successfully

**Comment by VinayHN1365466** [comment]
![image](https://github.com/user-attachments/assets/7a7028b8-a4b9-4cde-9e74-dc1b56006acb)

**Comment by VinayHN1365466** [comment]
no process are running

**Comment by VinayHN1365466** [comment]
![image](https://github.com/user-attachments/assets/121d0eae-12ca-438a-8d2c-756e770c3f9f)

**Comment by regisss** [comment]
Can you try adding `--privileged` to your `docker run` command?

**Comment by VinayHN1365466** [comment]
Thanks Regisss, I tried with --privileged with Docker, its still the same error 
![image](https://github.com/user-attachments/assets/5079a434-5daa-469e-9cd6-30c0834122f7)

**Comment by VinayHN1365466** [comment]
~/optimum-habana/examples/text-generation# python run_generation.py \
--model_name_or_path gpt2 \
--use_hpu_graphs \
--use_kv_cache \
--max_new_tokens 100 \
--do_sample \
--prompt "Here is my prompt"
/usr/lib/python3.10/inspect.py:288: FutureWarning: `torch.distributed.reduce_op` is deprecated, please use `torch.distributed.ReduceOp` instead
  return isinstance(object, types.FunctionType)
/usr/local/lib/python3.10/dist-packages/transformers/deepspeed.py:24: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
Fetching 1 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14665.40it/s]
Fetching 1 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 6316.72it/s]
12/16/2024 09:09:06 - INFO - __main__ - Single-device run.
/home/jenkins/workspace/cdsoftwarebuilder/create-binaries-from-sw-sources---bp-dt/repos/hcl/src/platform/gaudi_common/hcl_device_control_factory.cpp::84(initDevice): The condition [ g_ibv.init(deviceConfig) == hcclSuccess ] failed. ibv initialization failed
Traceback (most recent call last):
  File "/root/optimum-habana/examples/text-generation/run_generation.py", line 773, in <module>
    main()
  File "/root/optimum-habana/examples/text-generation/run_generation.py", line 384, in main
    model, assistant_model, tokenizer, generation_config = initialize_model(args, logger)
  File "/root/optimum-habana/examples/text-generation/utils.py", line 720, in initialize_model
    setup_model(args, model_dtype, model_kwargs, logger)
  File "/root/optimum-habana/examples/text-generation/utils.py", line 297, in setup_model
    model = model.eval().to(args.device)
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 2958, in to
    return super().to(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1177, in to
    return self._apply(convert)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 805, in _apply
    param_applied = fn(param)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1163, in convert
    return t.to(
RuntimeError: synStatus=26 [Generic failure] Device acquire failed.

**Comment by regisss** [comment]
Does running
```py
import torch
import habana_frameworks.torch.hpu

a = torch.tensor(1, device="hpu")
```
work?

**Comment by VinayHN1365466** [comment]
I got the same error 
/usr/lib/python3.10/inspect.py:288: FutureWarning: `torch.distributed.reduce_op` is deprecated, please use `torch.distributed.ReduceOp` instead
  return isinstance(object, types.FunctionType)
/home/jenkins/workspace/cdsoftwarebuilder/create-binaries-from-sw-sources---bp-dt/repos/hcl/src/platform/gaudi_common/hcl_device_control_factory.cpp::84(initDevice): The condition [ g_ibv.init(deviceConfig) == hcclSuccess ] failed. ibv initialization failed
Traceback (most recent call last):
  File "/root/optimum-habana/examples/text-generation/sample.py", line 4, in <module>
    a = torch.tensor(1, device="hpu")
RuntimeError: synStatus=26 [Generic failure] Device acquire failed.

**Comment by regisss** [comment]
Can you reboot this instance?

**Comment by VinayHN1365466** [comment]
Sorry, I don't have access to reboot the instance :(

**Comment by libinta** [comment]
@VinayHN1365466  can you capture dmesg -T ? thanks.

**Comment by yuanwu2017** [comment]
> no process are running

On some cloud machine, you need to add sudo to watch all process of other users.

**Comment by VinayHN1365466** [comment]
![image](https://github.com/user-attachments/assets/a434c0d0-5aaa-4b8c-9603-eee01c031d16)

**Comment by VinayHN1365466** [comment]
I rebooted the instance, but its still the same issue :(

**Comment by aneelaka-int** [comment]
Was this issue resolved? I am also seeing similar issue.

**Comment by regisss** [comment]
@aneelaka-int Running
```py
import torch
import habana_frameworks.torch.hpu

a = torch.tensor(1, device="hpu")
```
returns
```
RuntimeError: synStatus=26 [Generic failure] Device acquire failed.
```
?

**Comment by regisss** [comment]
Can you run `sudo dmesg  -T 2>&1 | tee dmesg.txt` and upload `dmesg.txt` here please?
