### ISSUE TITLE
Compute Accuracy in clip-roberta

### ISSUE THREAD

**Issue by skaulintel** [huggingface/optimum-habana#191]
### Feature request

Is it possible to include an accuracy metric when training clip-roberta?

### Motivation

We would like to have something other than loss to track during training and evaluation.

### Your contribution

I tried creating a dummy compute_metrics function to pass to GaudiTrainer thusly. 

    metric = evaluate.load("accuracy")
    def compute_metrics(p):
        return 1

get the following error:

```
Traceback (most recent call last):
  File "run_clip.py", line 553, in <module>
    main()
  File "run_clip.py", line 532, in main
    metrics = trainer.evaluate()
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 2932, in evaluate
    output = eval_loop(
  File "/usr/local/lib/python3.8/dist-packages/optimum/habana/transformers/trainer.py", line 1074, in evaluation_loop
    logits_dtype = get_dtype(logits)
  File "/usr/local/lib/python3.8/dist-packages/optimum/habana/transformers/trainer_utils.py", line 43, in get_dtype
    return [get_dtype(logits_tensor) for logits_tensor in logits]
  File "/usr/local/lib/python3.8/dist-packages/optimum/habana/transformers/trainer_utils.py", line 43, in <listcomp>
    return [get_dtype(logits_tensor) for logits_tensor in logits]
  File "/usr/local/lib/python3.8/dist-packages/optimum/habana/transformers/trainer_utils.py", line 45, in get_dtype
    raise TypeError(f"logits should be of type torch.Tensor or tuple, got {type(logits)} which is not supported")
TypeError: logits should be of type torch.Tensor or tuple, got <class 'transformers.modeling_outputs.BaseModelOutputWithPoolingAndCrossAttentions'> which is not supported
```

**Comment by regisss** [comment]
@skaulintel I'm going to investigate this and will let you know how to fix that.

**Comment by regisss** [comment]
Also, FYI, [here](https://github.com/huggingface/optimum-habana/blob/456096d9fd48f91b35fb82c860bb29a94158d93d/examples/image-classification/run_image_classification.py#L269) you can find an example of how to compute the accuracy.

**Comment by skaulintel** [comment]
Thanks, it gets past the TypeError now. How can I get the accuracy printed in the log? For example when this is printed:

**Comment by regisss** [comment]
@skaulintel You should get `eval_accuracy` in the metrics logged after evaluation. And if you want to run some validation steps during training, you can do it with the argument `--evaluation_strategy epoch` (in this example it will be run at the end of each epoch).

Or do you want to get the accuracy on the training set maybe?
