### ISSUE TITLE
htcore issue on "text-generation-inference" server with "langchain" client

### ISSUE THREAD

**Issue by htang2012** [huggingface/optimum-habana#338]
### System Info

```shell
optimum-habana                         1.6.1
text-generation                        0.6.0
text-generation-server                 0.9.2
langchain                              0.0.265
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Step to reproduce:
1. start text-generation-server following the instruction:
https://github.com/huggingface/optimum-habana/tree/main/text-generation-inference
2. launch bash in the docker,
3. inside the docker:
     pip install langchain text-generation
4. python run the following script:

from langchain import  HuggingFaceTextGenInference
llm = HuggingFaceTextGenInference(
    inference_server_url="http://127.0.0.1:80",
    max_new_tokens=64,
    top_k=10,
    top_p=0.95,
    typical_p=0.95,
    temperature=0.01,
    repetition_penalty=1.03,
)
output = llm("What is Machine Learning?")

print(output)

5. noticed: 
Client side:

Traceback (most recent call last):
  File "/root/langchain_client/langchain-client.py", line 12, in <module>
    output = llm("What is Machine Learning?")
  File "/usr/local/lib/python3.10/dist-packages/langchain/llms/base.py", line 802, in __call__
    self.generate(
  File "/usr/local/lib/python3.10/dist-packages/langchain/llms/base.py", line 598, in generate
    output = self._generate_helper(
  File "/usr/local/lib/python3.10/dist-packages/langchain/llms/base.py", line 504, in _generate_helper
    raise e
  File "/usr/local/lib/python3.10/dist-packages/langchain/llms/base.py", line 491, in _generate_helper
    self._generate(
  File "/usr/local/lib/python3.10/dist-packages/langchain/llms/base.py", line 977, in _generate
    self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/langchain/llms/huggingface_text_gen_inference.py", line 164, in _call
    res = self.client.generate(prompt, **invocation_params)
  File "/usr/local/lib/python3.10/dist-packages/text_generation/client.py", line 149, in generate
    raise parse_error(resp.status_code, payload)
text_generation.errors.GenerationError: Request failed during generation: Server error: name 'htcore' is not defined

Server side:

Traceback (most recent call last):
  File "/usr/local/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/usr/local/lib/python3.10/dist-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/typer/core.py", line 778, in main
    return _main(
  File "/usr/local/lib/python3.10/dist-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/text_generation_server/cli.py", line 66, in serve
    server.serve(model_id, revision, dtype, uds_path)
  File "/usr/local/lib/python3.10/dist-packages/text_generation_server/server.py", line 161, in serve
    asyncio.run(serve_inner(model_id, revision, dtype))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1896, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/dist-packages/grpc_interceptor/server.py", line 159, in invoke_intercept_method
    return await self.intercept(
> File "/usr/local/lib/python3.10/dist-packages/text_generation_server/interceptor.py", line 21, in intercept
    return await response
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor
    raise error
  File "/usr/local/lib/python3.10/dist-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
  File "/usr/local/lib/python3.10/dist-packages/text_generation_server/server.py", line 76, in Prefill
    generations, next_batch = self.model.generate_token(batch)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/text_generation_server/models/causal_lm.py", line 557, in generate_token
    next_token_id, logprobs = next_token_chooser(all_input_ids.view(1, -1), logits[-1:, :])
  File "/usr/local/lib/python3.10/dist-packages/text_generation_server/utils/tokens.py", line 65, in __call__
    scores, next_logprob = self.static_warper(scores)
  File "/usr/local/lib/python3.10/dist-packages/text_generation_server/utils/logits_process.py", line 51, in __call__
    self.hpu_graph = htcore.hpu.HPUGraph()
NameError: name 'htcore' is not defined

### Expected behavior

The expected behavior should run smoothly and provide the output text.

**Comment by htang2012** [comment]
@ try to understand this code segment, what is the intention of the this code?
if we would like to put lru_cache(..) on the setup of this callable, we need to put it above
def __init__(...),

or if we need to put lru_cache(...) on the actually call. we need to put it above:
def __call__(...), 

I believe that static_wraper(...) is not necessary, just point out for discussion.


class StaticWarper:
    def __init__(
        self,
        temperature=1.0,
        top_k=None,
        top_p=None,
        typical_p=None,
    ):

       ....
       import habana_frameworks.torch.core as htcore
       self.htcore = htcore

    def __call__(self, scores):
       .....

@lru_cache(10)
def static_warper(
    temperature: Optional[float],
    top_k: Optional[int],
    top_p: Optional[float],
    typical_p: Optional[float],
) -> StaticWarper:
    return StaticWarper(temperature=temperature, top_k=top_k, top_p=top_p, typical_p=typical_p)
