### ISSUE TITLE
Text Generation runtime error

### ISSUE THREAD

**Issue by danielfleischer** [huggingface/optimum-habana#614]
### System Info

```shell
Version: hl-1.13.0-rc-fw-47.0.0.0
Synapse: 1.13.0.463
optimum-habana: 1.9.0
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Running
> python run_generation.py --model_name_or_path meta-llama/Llama-2-7b-hf  --batch_size 1 --max_new_tokens 100 --use_hpu_graphs --prompt "Hi, how are you"

leads to runtime error:
> Traceback (most recent call last):
  File "run_generation.py", line 667, in <module>
    main()
  File "run_generation.py", line 464, in main
    generate()
  File "run_generation.py", line 444, in generate
    outputs = model.generate(
  File "/home/dan/habanalabs-venv/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/dan/habanalabs-venv/lib/python3.8/site-packages/optimum/habana/transformers/generation/utils.py", line 617, in generate
    and torch.sum(inputs_tensor[:, position] == generation_config.pad_token_id) > 0
RuntimeError: synNodeCreateWithId failed for node: pad_fwd_i32 with synStatus 26 [Generice failure]. .

### Expected behavior

Expected to generate new tokens, continuing the prompt.

**Comment by regisss** [comment]
Hi @danielfleischer! I cannot reproduce it with v1.9.0, could you try again with an install from source as follows?
```
pip install git+https://github.com/huggingface/optimum-habana.git
```

**Comment by danielfleischer** [comment]
Hi, installing from git, now package is `1.10.0.dev0`, getting the same error.

**Comment by regisss** [comment]
I cannot reproduce it. Could you provide the following pieces of information please?

- the output of the command `hl-smi`
- the complete log of your run
- the output of `pip list`

**Comment by danielfleischer** [comment]
Here you go:

<details>
<summary> hl-smi </summary>

```
+-----------------------------------------------------------------------------+
| HL-SMI Version:                           hl-1.13.0-rc-fw-47.0.0.0          |
| Driver Version:                                     1.13.0-ee32e42          |
|-------------------------------+----------------------+----------------------+
| AIP  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | AIP-Util  Compute M. |
|===============================+======================+======================|
|   0  HL-225              N/A  | 0000:33:00.0     N/A |                   0  |
| N/A   27C   N/A    75W / 600W |    768MiB / 98304MiB |     0%           N/A |
|-------------------------------+----------------------+----------------------+
|   1  HL-225              N/A  | 0000:9a:00.0     N/A |                   0  |
| N/A   27C   N/A    90W / 600W |    768MiB / 98304MiB |     0%           N/A |
|-------------------------------+----------------------+----------------------+
|   2  HL-225              N/A  | 0000:34:00.0     N/A |                   0  |
| N/A   30C   N/A    82W / 600W |    768MiB / 98304MiB |     0%           N/A |
|-------------------------------+----------------------+----------------------+
|   3  HL-225              N/A  | 0000:9b:00.0     N/A |                   0  |
| N/A   31C   N/A    91W / 600W |    768MiB / 98304MiB |     0%           N/A |
|-------------------------------+----------------------+----------------------+
|   4  HL-225              N/A  | 0000:4d:00.0     N/A |                   0  |
| N/A   32C   N/A    97W / 600W |    768MiB / 98304MiB |     1%           N/A |
|-------------------------------+----------------------+----------------------+
|   5  HL-225              N/A  | 0000:b3:00.0     N/A |                   0  |
| N/A   31C   N/A    78W / 600W |    768MiB / 98304MiB |     0%           N/A |
|-------------------------------+----------------------+----------------------+
|   6  HL-225              N/A  | 0000:4e:00.0     N/A |                   0  |
| N/A   27C   N/A    81W / 600W |    768MiB / 98304MiB |     0%           N/A |
|-------------------------------+----------------------+----------------------+
|   7  HL-225              N/A  | 0000:b4:00.0     N/A |                   0  |
| N/A   27C   N/A   100W / 600W |    768MiB / 98304MiB |     1%           N/A |
|-------------------------------+----------------------+----------------------+
| Compute Processes:                                               AIP Memory |
|  AIP       PID   Type   Process name                             Usage      |
|=============================================================================|
|   0        N/A   N/A    N/A                                      N/A        |
|   1        N/A   N/A    N/A                                      N/A        |
|   2        N/A   N/A    N/A                                      N/A        |
|   3        N/A   N/A    N/A                                      N/A        |
|   4        N/A   N/A    N/A                                      N/A        |
|   5        N/A   N/A    N/A                                      N/A        |
|   6        N/A   N/A    N/A                                      N/A        |
|   7        N/A   N/A    N/A                                      N/A        |
+=============================================================================+
```

</details>


<details>
<summary> log </summary>

```
(habanalabs-venv) text-generation [main●] pwd
/home/dan/optimum-habana/examples/text-generation
(habanalabs-venv) text-generation [main●] python run_generation.py --model_name_or_path meta-llama/Llama-2-7b-hf  --batch_size 1 --max_new_tokens 100 --use_hpu_graphs --prompt "Hi, how are you"
/home/dan/habanalabs-venv/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py:252: UserWarning: Device capability of hccl unspecified, assuming `cpu` and `cuda`. Please specify it via the `devices` argument of `register_backend`.
  warnings.warn(
Fetching 2 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 42581.77it/s]
Fetching 2 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 14742.72it/s]
01/03/2024 10:38:52 - INFO - __main__ - Single-device run.
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.97it/s]
============================= HABANA PT BRIDGE CONFIGURATION ===========================
 PT_HPU_LAZY_MODE = 1
 PT_RECIPE_CACHE_PATH =
 PT_CACHE_FOLDER_DELETE = 0
 PT_HPU_RECIPE_CACHE_CONFIG =
 PT_HPU_MAX_COMPOUND_OP_SIZE = 9223372036854775807
 PT_HPU_LAZY_ACC_PAR_MODE = 1
 PT_HPU_ENABLE_REFINE_DYNAMIC_SHAPES = 0
---------------------------: System Configuration :---------------------------
Num CPU Cores : 160
CPU RAM       : 1056389756 KB
------------------------------------------------------------------------------
01/03/2024 10:39:39 - INFO - __main__ - Args: Namespace(attn_softmax_bf16=False, bad_words=None, batch_size=1, bf16=False, bucket_size=-1, column_name=None, dataset_max_samples=-1, dataset_name=None, device='hpu', do_sample=False, force_words=None, fp8=False, global_rank=0, kv_cache_fp8=False, limit_hpu_graphs=False, local_rank=0, max_input_tokens=0, max_new_tokens=100, model_name_or_path='meta-llama/Llama-2-7b-hf', model_revision='main', n_iterations=5, num_beams=1, num_return_sequences=1, output_dir=None, peft_model=None, profiling_steps=0, profiling_warmup_steps=0, prompt=['Hi, how are you'], reduce_recompile=False, reuse_cache=False, seed=27, simulate_dyn_prompt=None, skip_hash_with_views=False, token=None, trim_logits=False, use_flash_attention=False, use_hpu_graphs=True, use_kv_cache=False, verbose_workers=False, warmup=3, world_size=0)
01/03/2024 10:39:39 - INFO - __main__ - device: hpu, n_hpu: 0, bf16: False
01/03/2024 10:39:39 - INFO - __main__ - Model initialization took 47.515s
01/03/2024 10:39:39 - INFO - __main__ - Graph compilation...
Warming up
/home/dan/habanalabs-venv/lib/python3.8/site-packages/transformers/generation/configuration_utils.py:362: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/dan/habanalabs-venv/lib/python3.8/site-packages/transformers/generation/configuration_utils.py:367: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
Traceback (most recent call last):
  File "run_generation.py", line 543, in <module>
    main()
  File "run_generation.py", line 320, in main
    generate(None, args.reduce_recompile)
  File "run_generation.py", line 297, in generate
    outputs = model.generate(
  File "/home/dan/habanalabs-venv/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/dan/habanalabs-venv/lib/python3.8/site-packages/optimum/habana/transformers/generation/utils.py", line 643, in generate
    and torch.sum(inputs_tensor[:, position] == generation_config.pad_token_id) > 0
RuntimeError: synNodeCreateWithId failed for node: pad_fwd_i32 with synStatus 26 [Generice failure]. .
```

</details>

<details>
<summary> pip list </summary>

```
Package                  Version
------------------------ ------------------
absl-py                  2.0.0
accelerate               0.25.0
aiohttp                  3.9.1
aiosignal                1.3.1
async-timeout            4.0.3
attrs                    23.2.0
av                       9.2.0
cachetools               5.3.2
certifi                  2023.11.17
cffi                     1.15.1
cfgv                     3.4.0
charset-normalizer       3.3.2
cmake                    3.28.1
coloredlogs              15.0.1
datasets                 2.14.7
diffusers                0.23.1
dill                     0.3.7
distlib                  0.3.8
expecttest               0.2.1
filelock                 3.13.1
frozenlist               1.4.1
fsspec                   2023.10.0
google-auth              2.25.2
google-auth-oauthlib     0.4.6
grpcio                   1.60.0
habana-gpu-migration     1.13.0.463
habana-media-loader      1.13.0.463
habana-pyhlml            1.13.0.463
habana-torch-dataloader  1.13.0.463
habana-torch-plugin      1.13.0.463
huggingface-hub          0.17.3
humanfriendly            10.0
identify                 2.5.33
idna                     3.6
importlib-metadata       7.0.1
intel-openmp             2023.2.3
Jinja2                   3.1.2
lightning                2.1.0
lightning-habana         1.2.0
lightning-utilities      0.10.0
Markdown                 3.5.1
MarkupSafe               2.1.3
mkl                      2023.1.0
mkl-include              2023.1.0
mpi4py                   3.1.4
mpmath                   1.3.0
multidict                6.0.4
multiprocess             0.70.15
networkx                 3.1
ninja                    1.11.1.1
nodeenv                  1.8.0
numpy                    1.23.5
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.18.1
nvidia-nvjitlink-cu12    12.3.101
nvidia-nvtx-cu12         12.1.105
oauthlib                 3.2.2
optimum                  1.16.1
optimum-habana           1.10.0.dev0
packaging                23.2
pandas                   2.0.1
pathspec                 0.12.1
peft                     0.7.1
perfetto                 0.7.0
Pillow                   10.1.0
Pillow-SIMD              7.0.0.post3
pip                      22.2.2
pkg_resources            0.0.0
platformdirs             4.1.0
pre-commit               3.3.3
protobuf                 3.20.3
psutil                   5.9.7
pyarrow                  14.0.2
pyarrow-hotfix           0.6
pyasn1                   0.5.1
pyasn1-modules           0.3.0
pybind11                 2.10.4
pycparser                2.21
pydantic                 1.10.13
pynvml                   8.0.4
python-dateutil          2.8.2
pytorch-lightning        2.1.3
pytz                     2023.3.post1
PyYAML                   6.0
regex                    2023.5.5
requests                 2.31.0
requests-oauthlib        1.3.1
rsa                      4.9
safetensors              0.4.1
sentencepiece            0.1.99
setuptools               69.0.3
six                      1.16.0
sympy                    1.12
tbb                      2021.11.0
tdqm                     0.0.1
tensorboard              2.11.2
tensorboard-data-server  0.6.1
tensorboard-plugin-wit   1.8.1
tokenizers               0.14.1
torch                    2.1.0a0+gitf8b6084
torch-tb-profiler        0.4.0
torchaudio               2.1.0+6ea1133
torchdata                0.7.0+c5f2204
torchmetrics             1.2.1
torchtext                0.16.0a0+4e255c9
torchvision              0.16.0+fbb4cc5
tqdm                     4.66.1
transformers             4.34.1
triton                   2.1.0
typing_extensions        4.9.0
tzdata                   2023.4
urllib3                  1.26.18
virtualenv               20.25.0
Werkzeug                 3.0.1
wheel                    0.42.0
xxhash                   3.4.1
yamllint                 1.33.0
yarl                     1.9.4
zipp                     3.17.0
```

</details>

Thanks for following this.

**Comment by regisss** [comment]
I don't see where that could come from.
Could you try to run it again inside a Docker container? [Here](https://docs.habana.ai/en/latest/Installation_Guide/Bare_Metal_Fresh_OS.html#run-using-containers) are the instructions to pull the Docker image and run it. It's possible Docker is already configured on your instance so you just have to pull/run Docker images as described [here](https://docs.habana.ai/en/latest/Installation_Guide/Bare_Metal_Fresh_OS.html#pull-and-launch-docker-image-habana-vault).

**Comment by danielfleischer** [comment]
Running inside a docker image works and text is generated. I'll work inside the image from now on.

**Comment by regisss** [comment]
Nice!
I think there must be an issue in the setup of some Habana libraries in your environment.
