### ISSUE TITLE
Error while saving checkpoint with trainer

### ISSUE THREAD

**Issue by dittops** [huggingface/optimum-habana#744]
### System Info

```shell
optimum-habana==1.10.4
docker: vault.habana.ai/gaudi-docker/1.14.0/ubuntu22.04/habanalabs/pytorch-installer-2.1.1:latest
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

I'm running a training with the following command. The script uses GaudiTrainer.

```
deepspeed train-gaudi.py \
--base_model budecosystem/boomer-1b \
--output_dir output/test \
--data_path roneneldan/TinyStories \
--learning_rate 2e-3 \
--num_train_epochs 1 \
--per_device_train_batch_size 12 \
--gradient_accumulation_steps 1 \
--lr_scheduler_type cosine \
--warmup_ratio 0.1 \
--report_to wandb \
--logging_steps 10 \
--save_strategy steps \
--save_steps 10 \
--save_total_limit 2 \
--use_habana \
--gaudi_config_name gaudi_config.json \
--deepspeed ds_config.json \
```

But while saving the checkpoint, i'm getting the following error.

```
Traceback (most recent call last):
  File "/root/bud-experiments/train-gaudi.py", line 222, in <module>
    train()
  File "/root/bud-experiments/train-gaudi.py", line 215, in train
    trainer.train(resume_from_checkpoint=False)
  File "/usr/local/lib/python3.10/dist-packages/optimum/habana/transformers/trainer.py", line 509, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.10/dist-packages/optimum/habana/transformers/trainer.py", line 984, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/usr/local/lib/python3.10/dist-packages/optimum/habana/transformers/trainer.py", line 1167, in _maybe_log_save_evaluate
    self._save_checkpoint(model, trial, metrics=metrics)
  File "/usr/local/lib/python3.10/dist-packages/optimum/habana/transformers/trainer.py", line 1237, in _save_checkpoint
    self._save_optimizer_and_scheduler(staging_output_dir)
  File "/usr/local/lib/python3.10/dist-packages/optimum/habana/transformers/trainer.py", line 1319, in _save_optimizer_and_scheduler
    self.model_wrapped.save_checkpoint(output_dir)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 3125, in save_checkpoint
    self._save_zero_checkpoint(save_dir, tag)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 3483, in _save_zero_checkpoint
    self.checkpoint_engine.save(zero_sd, zero_checkpoint_name)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/checkpoint_engine/torch_checkpoint_engine.py", line 22, in save
    torch.save(state_dict, path)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 617, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol, _disable_byteorder_record)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 829, in _save
    pickler.dump(obj)
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor.py", line 224, in __reduce_ex__
    return self._reduce_ex_internal(proto)
  File "/usr/local/lib/python3.10/dist-packages/habana_frameworks/torch/core/torch_overwrites.py", line 376, in _reduce_ex_internal_habana
    func, args = _original_reduce_ex_internal(self, proto)
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor.py", line 280, in _reduce_ex_internal
    self.cpu().numpy()
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
```

### Expected behavior

Expected to save the checkpoint without any issue

**Comment by regisss** [comment]
Can you share `train-gaudi.py`, `gaudi_config.json` and `ds_config.json` please? Or at least a minimal  script that enables me to reproduce this error.

**Comment by dittops** [comment]
If I remove the deepspeed config from the command, the loss becomes nan.
<img width="1402" alt="image" src="https://github.com/huggingface/optimum-habana/assets/12937285/f15887e3-ce32-424b-a97a-a3b798b38aa3">

**Comment by dittops** [comment]
ds_config.json

```
{
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "gradient_accumulation_steps": "auto",
    "gradient_clipping": "auto",
    "zero_allow_untested_optimizer": true,
    "fp16": {
      "enabled": "auto",
      "loss_scale": 0,
      "initial_scale_power": 16,
      "loss_scale_window": 1000,
      "hysteresis": 2,
      "min_loss_scale": 1
    },  
    "zero_optimization": {
      "stage": 2,
      "allgather_partitions": true,
      "allgather_bucket_size": 5e8,
      "reduce_scatter": true,
      "reduce_bucket_size": 5e8,
      "overlap_comm": false,
      "contiguous_gradients": true,
      "stage3_gather_16bit_weights_on_model_save": true
    }
  }
```

gaudi_config.json
```
{
    "use_fused_adam": true,
    "use_fused_clip_norm": true,
    "use_torch_autocast": true
}
```

train-gaudi.py
```
import pickle
import os
from dataclasses import dataclass, field
from typing import Optional
from itertools import chain

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, Trainer, TrainingArguments, HfArgumentParser, DataCollatorForSeq2Seq     
from datasets import load_dataset
from optimum.habana import GaudiTrainer, GaudiTrainingArguments

from model.llama import convert_llama_model, convert_llama_with_temperature


IGNORE_INDEX = -100

@dataclass
class ModelArguments:
    base_model: Optional[str] = field(default="base-model")
    use_lambda: Optional[bool] = field(default=False)
    temperature: Optional[float] = field(default=1)

@dataclass
class DataArguments:
    data_path: str = field(
      default=None, metadata={"help": "Path to the training data."}
    )
    max_seq_length = 2048
    is_tokenized: Optional[bool] = field(default=False)
    system_col: Optional[str] = field(default="")
    input_col: Optional[str] = field(default="input")
    target_col: Optional[str] = field(default="target")

@dataclass
class TrainArguments(GaudiTrainingArguments):
    per_device_train_batch_size = 2
    gradient_accumulation_steps = 1
    num_train_epochs = 3
    learning_rate = 2e-5
    fp16 = True
    logging_steps = 10
    optim = "adamw_torch"
    save_strategy = "epoch"
    output_dir = 'bud-1b'
    save_total_limit = 5
    report_to = 'wandb'
    adam_beta1 = 0.9
    adam_beta2 = 0.95
    stage: Optional[str] = field(default="pretrain")

def get_prompt(input, system = '', target = ''):
    # if not system:
    #     system = "A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions."

    prompt_template = f"""{system}
    
    ### Instruction:
    {input}

    ### Response:
    {target}"""

    return prompt_template

def load_data(tokenizer, dataset, max_length, stage, system_col, input_col, target_col):
    

    def preprocess_pretrain_dataset(examples):

        text_ids = tokenizer(
            examples["text"],
            add_special_tokens=False)["input_ids"]

        concatenated_ids = list(chain(*text_ids))
        total_length = len(concatenated_ids)
        
        block_size = max_length
        # we drop the small remainder, and if the total_length < block_size, we exclude this batch
        total_length = (total_length // block_size) * block_size
        # split by chunks of max_source_length
        result = [concatenated_ids[i: i + block_size]
                  for i in range(0, total_length, block_size)]
        
        return {
            "input_ids": result,
            "labels": result.copy()
        }

    def preprocess_supervised_dataset(examples):
        #data format = {"prompt":"", "response": "", "history": []}
        
        model_inputs = {"input_ids": [], "labels": [], "attention_mask": []}

        for i in range(len(examples[input_col])):
            input_ids, labels = [], []
            if system_col:
                source = get_prompt(examples[input_col][i], examples[system_col][i])
            else:
                source = get_prompt(examples[input_col][i])
            source_ids = tokenizer.encode(text=source, add_special_tokens=False)
            target_ids = tokenizer.encode(text=examples[target_col][i], add_special_tokens=False)
            input_ids += [tokenizer.bos_token_id] + source_ids + target_ids + [tokenizer.eos_token_id]
            labels += [IGNORE_INDEX] * (len(source_ids) + 1) + target_ids + [tokenizer.eos_token_id]

            if len(input_ids) > max_length:
                input_ids = input_ids[:max_length]
                labels = labels[:max_length]

            model_inputs["input_ids"].append(input_ids)
            model_inputs["labels"].append(labels)
            model_inputs["attention_mask"].append([1] * len(input_ids))
        
        return model_inputs
    
    def print_supervised_dataset_example(example):
        print("input_ids:\n{}".format(example["input_ids"]))
        print("inputs:\n{}".format(tokenizer.decode(example["input_ids"], skip_special_tokens=False)))
        print("label_ids:\n{}".format(example["labels"]))
        print("labels:\n{}".format(tokenizer.decode([
            token_id if token_id != -100 else tokenizer.pad_token_id for token_id in example["labels"]
        ], skip_special_tokens=False)))
    
    if stage == 'pretrain':
        map_func = preprocess_pretrain_dataset
    else:
        map_func = preprocess_supervised_dataset

    column_names = dataset.column_names
    dataset = dataset.map(
        map_func,
        batched=True,
        remove_columns=column_names,
        num_proc=64
    )

    # print_supervised_dataset_example(dataset[0])
    print(len(dataset))

    return {
        "train_dataset": dataset
    }


def train():

    os.environ["WANDB_PROJECT"] = 'gaudi-pretrain-exp'

    # convert_llama_with_temperature()
    
    parser = HfArgumentParser(
        (ModelArguments, DataArguments, TrainArguments)
    )
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
    

    tokenizer = AutoTokenizer.from_pretrained(model_args.base_model, trust_remote_code=True)
    tokenizer.pad_token_id = 0

    model = AutoModelForCausalLM.from_pretrained(
        model_args.base_model,
        # device_map="auto",
        torch_dtype=torch.float16,
        # use_flash_attention_2=True,
        # attn_implementation="flash_attention_2",
        trust_remote_code=True
    )

    if model_args.use_lambda:
        local_branch = data_args.max_seq_length
        global_branch = 100
        model = convert_llama_model(model, local_branch, global_branch)
        print('Added lambda attention')

    total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print("total params: ", total_params)


    if data_args.data_path.endswith(".json") or data_args.data_path.endswith(".jsonl"):
        data = load_dataset("json", data_files=data_args.data_path)
    elif data_args.data_path.endswith(".pkl"):
        with open(data_args.data_path, "rb") as file:
            data = pickle.load(file)
    else:
        data = load_dataset(data_args.data_path)
    
    if data_args.is_tokenized:
        dataset = {
            "train_dataset": data["train"]
        }
    else:
        dataset =  load_data(
            tokenizer, 
            data['train'], 
            data_args.max_seq_length, 
            training_args.stage, 
            data_args.system_col,
            data_args.input_col,
            data_args.target_col
        )
    
    data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer)

    trainer = GaudiTrainer(
        model=model, 
        tokenizer=tokenizer, 
        args=training_args, 
        data_collator=data_collator,
        **dataset
    )
    # if list(pathlib.Path(training_args.output_dir).glob("checkpoint-*")):
    #     trainer.train(resume_from_checkpoint=True)
    # else:
    #     trainer.train()
    model.config.use_cache = False
    trainer.train(resume_from_checkpoint=False)
    
    trainer.save_model()



if __name__ == "__main__":
    train()
```

**Comment by dittops** [comment]
I have reinstalled deepspeed from https://github.com/HabanaAI/DeepSpeed and then enabled bf16. Now, I'm not having the issue. So I assume it was an issue with deepspeed version.

**Comment by regisss** [comment]
@dittops I see you reopened this issue, are you still facing an error when running this script?

**Comment by dittops** [comment]
Yes, I forgot to share the error. I'm getting the below error while starting the training. I think this is thrown while trying to execute the first step.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 2051, in all_reduce
    work = group.allreduce([tensor], opts)
RuntimeError: Graph compile failed. synStatus=synStatus 26 [Generice failure]. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/bud-experiments/train-gaudi.py", line 223, in <module>
    train()
  File "/root/bud-experiments/train-gaudi.py", line 216, in train
    trainer.train(resume_from_checkpoint=False)
  File "/usr/local/lib/python3.10/dist-packages/optimum/habana/transformers/trainer.py", line 509, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.10/dist-packages/optimum/habana/transformers/trainer.py", line 915, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/usr/local/lib/python3.10/dist-packages/optimum/habana/transformers/trainer.py", line 1488, in training_step
    self.accelerator.backward(loss)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 1960, in backward
    self.deepspeed_engine_wrapped.backward(loss, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/deepspeed.py", line 167, in backward
    self.engine.backward(loss, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 1996, in backward
    self.optimizer.backward(loss, retain_graph=retain_graph)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 2086, in backward
    self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/fp16/loss_scaler.py", line 63, in backward
    scaled_loss.backward(retain_graph=retain_graph)
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor.py", line 502, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 899, in reduce_partition_and_remove_grads
    self.reduce_ready_partitions_and_remove_grads(param, i)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1413, in reduce_ready_partitions_and_remove_grads
    self.reduce_independent_p_g_buckets_and_remove_grads(param, i)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 928, in reduce_independent_p_g_buckets_and_remove_grads
    self.reduce_ipg_grads()
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1364, in reduce_ipg_grads
    self.average_tensor(self.ipg_buffer[self.ipg_index].narrow(0, 0, self.elements_in_ipg_bucket))
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1044, in average_tensor
    self.gradient_reduction_w_predivide(tensor)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 979, in gradient_reduction_w_predivide
    dist.all_reduce(tensor_to_allreduce, group=self.dp_process_group)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/comm/comm.py", line 117, in log_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/comm/comm.py", line 496, in all_reduce
    return cdb.all_reduce(tensor, op, group, async_op)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/comm/torch.py", line 153, in all_reduce
    return torch.distributed.all_reduce(tensor=tensor, op=op, group=group, async_op=async_op)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 52, in wrapper
    "args": f"{args}, {kwargs}",
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor.py", line 441, in __repr__
    return torch._tensor_str._str(self, tensor_contents=tensor_contents)
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor_str.py", line 664, in _str
    return _str_intern(self, tensor_contents=tensor_contents)
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor_str.py", line 595, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor_str.py", line 347, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor_str.py", line 137, in __init__
    nonzero_finite_vals = torch.masked_select(
RuntimeError: Empty tensor optional
```

**Comment by regisss** [comment]
Can you show me the output of `pip list` in your environment please?
Do you still use the script and configs above with the same command line?

**Comment by dittops** [comment]
I have updated the config to enable bf16. Please see the updated details

ds_config.json
```
{
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "gradient_accumulation_steps": "auto",
    "gradient_clipping": "auto",
    "zero_allow_untested_optimizer": true,
    "bf16": {
      "enabled": true,
      "loss_scale": 0,
      "initial_scale_power": 16,
      "loss_scale_window": 1000,
      "hysteresis": 2,
      "min_loss_scale": 1
    },  
    "zero_optimization": {
      "stage": 2,
      "allgather_partitions": true,
      "allgather_bucket_size": 5e8,
      "reduce_scatter": true,
      "reduce_bucket_size": 5e8,
      "overlap_comm": false,
      "contiguous_gradients": true,
      "stage3_gather_16bit_weights_on_model_save": true
    }
  }
```

gaudi_config.json
```
{
    "use_fused_adam": true,
    "use_fused_clip_norm": true,
    "use_torch_autocast": true,
    "use_habana_mixed_precision": true
}
```

Pip list
```
Package                     Version
--------------------------- --------------------------
absl-py                     2.1.0
accelerate                  0.27.2
aiohttp                     3.9.1
aiosignal                   1.3.1
appdirs                     1.4.4
async-timeout               4.0.3
attrs                       23.2.0
av                          9.2.0
cachetools                  5.3.2
certifi                     2023.11.17
cffi                        1.15.1
cfgv                        3.4.0
charset-normalizer          3.3.2
click                       8.1.7
cmake                       3.28.1
coloredlogs                 15.0.1
datasets                    2.17.1
deepspeed                   0.12.4+hpu.synapse.v1.14.0
diffusers                   0.26.3
dill                        0.3.8
distlib                     0.3.8
docker-pycreds              0.4.0
exceptiongroup              1.2.0
expecttest                  0.2.1
filelock                    3.13.1
frozenlist                  1.4.1
fsspec                      2023.10.0
gitdb                       4.0.11
GitPython                   3.1.42
google-auth                 2.26.2
google-auth-oauthlib        0.4.6
grpcio                      1.60.0
habana_gpu_migration        1.14.0.493
habana-media-loader         1.14.0.493
habana-pyhlml               1.14.0.493
habana_quantization_toolkit 1.14.0.493
habana-torch-dataloader     1.14.0.493
habana-torch-plugin         1.14.0.493
hjson                       3.1.0
huggingface-hub             0.21.2
humanfriendly               10.0
identify                    2.5.33
idna                        3.6
importlib-metadata          7.0.1
iniconfig                   2.0.0
intel-openmp                2023.2.3
Jinja2                      3.1.3
jsonlines                   4.0.0
lightning                   2.1.2
lightning-habana            1.3.0
lightning-utilities         0.10.1
Markdown                    3.5.2
MarkupSafe                  2.1.4
mkl                         2023.1.0
mkl-include                 2023.1.0
mpi4py                      3.1.4
mpmath                      1.3.0
multidict                   6.0.4
multiprocess                0.70.16
networkx                    3.2.1
ninja                       1.11.1.1
nodeenv                     1.8.0
numpy                       1.23.5
oauthlib                    3.2.2
optimum                     1.17.1
optimum-habana              1.10.4
packaging                   23.2
pandas                      2.0.1
pathspec                    0.12.1
perfetto                    0.7.0
pillow                      10.2.0
Pillow-SIMD                 7.0.0.post3
pip                         23.3.1
platformdirs                4.1.0
pluggy                      1.3.0
pre-commit                  3.3.3
protobuf                    3.20.3
psutil                      5.9.8
py-cpuinfo                  9.0.0
pyarrow                     15.0.0
pyarrow-hotfix              0.6
pyasn1                      0.5.1
pyasn1-modules              0.3.0
pybind11                    2.10.4
pycparser                   2.21
pydantic                    1.10.13
pynvml                      8.0.4
pytest                      7.4.4
python-dateutil             2.8.2
python-dotenv               1.0.1
pytorch-lightning           2.1.3
pytz                        2023.3.post1
PyYAML                      6.0
regex                       2023.5.5
requests                    2.31.0
requests-oauthlib           1.3.1
rsa                         4.9
safetensors                 0.4.2
sentencepiece               0.2.0
sentry-sdk                  1.40.6
setproctitle                1.3.3
setuptools                  69.0.3
six                         1.16.0
smmap                       5.0.1
sympy                       1.12
tbb                         2021.11.0
tdqm                        0.0.1
tensorboard                 2.11.2
tensorboard-data-server     0.6.1
tensorboard-plugin-wit      1.8.1
tokenizers                  0.15.2
tomli                       2.0.1
torch                       2.1.1a0+gitb51c9f6
torch_tb_profiler           0.4.0
torchaudio                  2.1.0+6ea1133
torchdata                   0.7.0+c5f2204
torchmetrics                1.3.0.post0
torchtext                   0.16.0a0+4e255c9
torchvision                 0.16.0+fbb4cc5
tqdm                        4.66.1
transformers                4.37.2
typing_extensions           4.9.0
tzdata                      2023.4
urllib3                     1.26.18
virtualenv                  20.25.0
wandb                       0.16.3
Werkzeug                    3.0.1
wheel                       0.42.0
xxhash                      3.4.1
yamllint                    1.33.0
yarl                        1.9.4
zipp                        3.17.0
```

**Comment by regisss** [comment]
I can't run your script because of
```py
from model.llama import convert_llama_model, convert_llama_with_temperature
```
which I guess is some custom code.

What I would first try is to change the DeepSpeed config. It seems you want to use ZeRO-2 but some arguments are specific to ZeRO-3 (e.g. `stage3_gather_16bit_weights_on_model_save`). Can you try with [this DeepSpeed config](https://github.com/huggingface/optimum-habana/blob/main/tests/configs/deepspeed_zero_2.json) and let me know what you get?

**Comment by dittops** [comment]
I have tried this. But getting the same error. 

The custom code is not used in the current configuration. Here is the updated code commenting those lines.

```
import pickle
import os
from dataclasses import dataclass, field
from typing import Optional
from itertools import chain

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, Trainer, TrainingArguments, HfArgumentParser, DataCollatorForSeq2Seq     
from datasets import load_dataset
from optimum.habana import GaudiTrainer, GaudiTrainingArguments

# from model.llama import convert_llama_model, convert_llama_with_temperature


IGNORE_INDEX = -100

@dataclass
class ModelArguments:
    base_model: Optional[str] = field(default="base-model")
    use_lambda: Optional[bool] = field(default=False)
    temperature: Optional[float] = field(default=1)

@dataclass
class DataArguments:
    data_path: str = field(
      default=None, metadata={"help": "Path to the training data."}
    )
    max_seq_length = 2048
    is_tokenized: Optional[bool] = field(default=False)
    system_col: Optional[str] = field(default="")
    input_col: Optional[str] = field(default="input")
    target_col: Optional[str] = field(default="target")

@dataclass
class TrainArguments(GaudiTrainingArguments):
    per_device_train_batch_size = 2
    gradient_accumulation_steps = 1
    num_train_epochs = 3
    learning_rate = 2e-5
    fp16 = True
    logging_steps = 10
    optim = "adamw_torch"
    save_strategy = "epoch"
    output_dir = 'bud-1b'
    save_total_limit = 5
    report_to = 'wandb'
    adam_beta1 = 0.9
    adam_beta2 = 0.95
    stage: Optional[str] = field(default="pretrain")

def get_prompt(input, system = '', target = ''):
    # if not system:
    #     system = "A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions."

    prompt_template = f"""{system}
    
    ### Instruction:
    {input}

    ### Response:
    {target}"""

    return prompt_template

def load_data(tokenizer, dataset, max_length, stage, system_col, input_col, target_col):
    

    def preprocess_pretrain_dataset(examples):

        text_ids = tokenizer(
            examples["text"],
            add_special_tokens=False)["input_ids"]

        concatenated_ids = list(chain(*text_ids))
        total_length = len(concatenated_ids)
        
        block_size = max_length
        # we drop the small remainder, and if the total_length < block_size, we exclude this batch
        total_length = (total_length // block_size) * block_size
        # split by chunks of max_source_length
        result = [concatenated_ids[i: i + block_size]
                  for i in range(0, total_length, block_size)]
        
        return {
            "input_ids": result,
            "labels": result.copy()
        }

    def preprocess_supervised_dataset(examples):
        #data format = {"prompt":"", "response": "", "history": []}
        
        model_inputs = {"input_ids": [], "labels": [], "attention_mask": []}

        for i in range(len(examples[input_col])):
            input_ids, labels = [], []
            if system_col:
                source = get_prompt(examples[input_col][i], examples[system_col][i])
            else:
                source = get_prompt(examples[input_col][i])
            source_ids = tokenizer.encode(text=source, add_special_tokens=False)
            target_ids = tokenizer.encode(text=examples[target_col][i], add_special_tokens=False)
            input_ids += [tokenizer.bos_token_id] + source_ids + target_ids + [tokenizer.eos_token_id]
            labels += [IGNORE_INDEX] * (len(source_ids) + 1) + target_ids + [tokenizer.eos_token_id]

            if len(input_ids) > max_length:
                input_ids = input_ids[:max_length]
                labels = labels[:max_length]

            model_inputs["input_ids"].append(input_ids)
            model_inputs["labels"].append(labels)
            model_inputs["attention_mask"].append([1] * len(input_ids))
        
        return model_inputs
    
    def print_supervised_dataset_example(example):
        print("input_ids:\n{}".format(example["input_ids"]))
        print("inputs:\n{}".format(tokenizer.decode(example["input_ids"], skip_special_tokens=False)))
        print("label_ids:\n{}".format(example["labels"]))
        print("labels:\n{}".format(tokenizer.decode([
            token_id if token_id != -100 else tokenizer.pad_token_id for token_id in example["labels"]
        ], skip_special_tokens=False)))
    
    if stage == 'pretrain':
        map_func = preprocess_pretrain_dataset
    else:
        map_func = preprocess_supervised_dataset

    column_names = dataset.column_names
    dataset = dataset.map(
        map_func,
        batched=True,
        remove_columns=column_names,
        num_proc=64
    )

    # print_supervised_dataset_example(dataset[0])
    print(len(dataset))

    return {
        "train_dataset": dataset
    }


def train():

    os.environ["WANDB_PROJECT"] = 'gaudi-pretrain-exp'

    # convert_llama_with_temperature()
    
    parser = HfArgumentParser(
        (ModelArguments, DataArguments, TrainArguments)
    )
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
    

    tokenizer = AutoTokenizer.from_pretrained(model_args.base_model, trust_remote_code=True)
    tokenizer.pad_token_id = 0

    model = AutoModelForCausalLM.from_pretrained(
        model_args.base_model,
        # device_map="auto",
        torch_dtype=torch.float16,
        # use_flash_attention_2=True,
        # attn_implementation="flash_attention_2",
        trust_remote_code=True
    )

    # if model_args.use_lambda:
    #     local_branch = data_args.max_seq_length
    #     global_branch = 100
    #     model = convert_llama_model(model, local_branch, global_branch)
    #     print('Added lambda attention')

    total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print("total params: ", total_params)


    if data_args.data_path.endswith(".json") or data_args.data_path.endswith(".jsonl"):
        data = load_dataset("json", data_files=data_args.data_path)
    elif data_args.data_path.endswith(".pkl"):
        with open(data_args.data_path, "rb") as file:
            data = pickle.load(file)
    else:
        data = load_dataset(data_args.data_path)
    
    if data_args.is_tokenized:
        dataset = {
            "train_dataset": data["train"]
        }
    else:
        with training_args.main_process_first(desc="dataset map tokenization"):
            dataset =  load_data(
                tokenizer, 
                data['train'], 
                data_args.max_seq_length, 
                training_args.stage, 
                data_args.system_col,
                data_args.input_col,
                data_args.target_col
            )
    
    data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer)

    trainer = GaudiTrainer(
        model=model, 
        tokenizer=tokenizer, 
        args=training_args, 
        data_collator=data_collator,
        **dataset
    )
    # if list(pathlib.Path(training_args.output_dir).glob("checkpoint-*")):
    #     trainer.train(resume_from_checkpoint=True)
    # else:
    #     trainer.train()
    model.config.use_cache = False
    trainer.train(resume_from_checkpoint=False)
    
    trainer.save_model()



if __name__ == "__main__":
    train()
```

**Comment by regisss** [comment]
It seems to just be an out-of-memory error. Try a smaller batch size (2 works) and/or use gradient checkpointing (even though a batch size of 12 with gradient checkpointing still is too much on Gaudi1).

**Comment by dittops** [comment]
Thanks for the update, this seems resolved now.
