### ISSUE TITLE
Upgrade DPO and PPO to support trl v0.7.8 or higher

### ISSUE THREAD

**Issue by skavulya** [huggingface/optimum-habana#784]
### Feature request

We need trl v0.7.8 or higher to support stable diffusion finetuning with DDPO in https://github.com/huggingface/optimum-habana/pull/733. 

### Motivation

TRL v0.7.6 conflicts with diffusers v0.26.0 required for LoRA-based finetuning of stable diffusion with DDPO. 

However, upgrading to v0.7.8 or higher causes the following error in dpo and ppo.

Traceback (most recent call last):
  File "/root/optimum-habana/examples/trl/sft.py", line 153, in <module>
    trainer = GaudiSFTTrainer(
  File "/root/optimum-habana/optimum/habana/trl/trainer/sft_trainer.py", line 143, in __init__
    model = get_peft_model(model, peft_config)
  File "/usr/local/lib/python3.10/dist-packages/peft/mapping.py", line 116, in get_peft_model
    return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config, adapter_name=adapter_name)
  File "/usr/local/lib/python3.10/dist-packages/peft/peft_model.py", line 973, in __init__
    super().__init__(model, peft_config, adapter_name)
  File "/usr/local/lib/python3.10/dist-packages/peft/peft_model.py", line 121, in __init__
    self.base_model = cls(model, {adapter_name: peft_config}, adapter_name)
  File "/usr/local/lib/python3.10/dist-packages/peft/tuners/lora/model.py", line 111, in __init__
    super().__init__(model, config, adapter_name)
  File "/usr/local/lib/python3.10/dist-packages/peft/tuners/tuners_utils.py", line 94, in __init__
    self.inject_adapter(self.model, adapter_name)
  File "/usr/local/lib/python3.10/dist-packages/peft/tuners/tuners_utils.py", line 254, in inject_adapter
    raise ValueError(
ValueError: Target modules {'v_proj', 'q_proj'} not found in the base model. Please check the target modules and try again.

### Your contribution

I can help with the implementation

**Comment by regisss** [comment]
I couldn't reproduce this error, can you share the command you executed please?

**Comment by skavulya** [comment]
Thanks @regisss for looking into it.  I'm also unable to reproduce it. I think there might have been something wrong with my Python environment.
